[custom]
; Crl规则-在线更新版
enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=base/default.yaml


custom_proxy_group=🚀 节点选择`select`[]All-US`[]All-JP`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=☑️ 手动切换`select`.*
custom_proxy_group=🤖 Ai`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]All-US`[]All-JP`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`60
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=📢 Google`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ GitHub`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换
custom_proxy_group=All-US`fallback`(?i)US`http://www.gstatic.com/generate_204`30
custom_proxy_group=All-JP`fallback`(?i)JP`http://www.gstatic.com/generate_204`30



ruleset=🎯 全球直连,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/Coke.list
;ruleset=REJECT,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/AdvertisingLite.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/YouTube.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/GoogleFCM.list
ruleset=📢 Google,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/Google.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/GlobalMedia.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/Telegram.list
ruleset=🤖 Ai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=🤖 Ai,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/Ai.list
ruleset=Ⓜ️ GitHub,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/GitHub.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/Microsoft.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/Proxy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Direct/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/GameDownload.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/duahilong/CokeRuleList-CRL/refs/heads/main/crl/ChinaIP.list
; 兜底规则（可选）：建议加上，确保没被规则覆盖到的流量有去处
ruleset=🚀 节点选择,[]MATCH
