name: Auto Update Rules

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
  push:
    paths:
      - "rule.json"
      - "app/**"
      - "main.py"
      - ".github/workflows/main.yml"
      - "tests/**"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 3. Install Dependencies
        run: pip install requests

      - name: 4. Run Unit Tests
        run: python -m unittest discover -s tests -v

      - name: 5. Build Rules
        run: python main.py

      - name: 6. Commit And Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add crl/*.list crl/tx.log
          git commit -m "Auto Update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
